apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-prd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rik2803/argocd-test.git
    path: kustomize-app/overlays/production
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
